import { IPmEtablissement, NewPmEtablissement } from './pm-etablissement.model';

export const sampleWithRequiredData: IPmEtablissement = {
  id: 24935,
  idEtablissementRPG: 'inasmuch',
  codePartenaireDistributeur: 'gee excepting brochure',
  numeroSiretSiege: 'allegation um er',
  codeEtat: 'all hurtful',
  libelleEtat: 'shrilly gee amidst',
  codeCategoriePersonne: 'boring beneath cutlet',
  libelleCategoriePersonne: 'gee aw',
  codeType: 'meh',
  dateCreationJuridique: 'lace',
  dateEtat: 'verbally hence given',
  dateFermetureJuridique: 'certify only scratch',
  codeIDCC: 'dead',
  codeTrancheEffectif: 'gosh forenenst',
  libelleTrancheEffectif: 'whenever yak t-shirt',
  dateCessationActivite: 'fooey astride ack',
  dateEffectifOfficiel: 'of desk because',
  effectifOfficiel: 'dimly before',
  codeMotifCessationActivite: 'pitiful pro',
  siret: 'approach',
  codeTypeEtablissement: 'telescope',
  libelleEnseigne: 'immediately afore notwithstanding',
  codeNIC: 'excluding pish',
};

export const sampleWithPartialData: IPmEtablissement = {
  id: 5384,
  idEtablissementRPG: 'when',
  codePartenaireDistributeur: 'scuffle ah',
  numeroSiretSiege: 'quinoa pear',
  codeEtat: 'phooey ick commercial',
  libelleEtat: 'whoa apud arrogantly',
  codeCategoriePersonne: 'midst than carefree',
  libelleCategoriePersonne: 'anenst resort',
  codeType: 'throughout times',
  dateCreationJuridique: 'pish',
  dateEtat: 'gee lazily unnecessarily',
  dateFermetureJuridique: 'incline fake',
  codeIDCC: 'jubilantly',
  codeTrancheEffectif: 'ha',
  libelleTrancheEffectif: 'wherever aha',
  dateCessationActivite: 'pity for',
  dateEffectifOfficiel: 'account mmm garrote',
  effectifOfficiel: 'yogurt',
  codeMotifCessationActivite: 'ha stool drat',
  siret: 'scented',
  codeTypeEtablissement: 'dishearten baritone yawningly',
  libelleEnseigne: 'ew knowledgeably boo',
  codeNIC: 'window',
};

export const sampleWithFullData: IPmEtablissement = {
  id: 22674,
  idEtablissementRPG: 'if yippee',
  codePartenaireDistributeur: 'pry task instead',
  numeroSiretSiege: 'good-natured ironclad',
  codeEtat: 'offset ugh fooey',
  libelleEtat: 'crackle wrongly',
  codeCategoriePersonne: 'for',
  libelleCategoriePersonne: 'tight marksman failing',
  codeType: 'er dress onto',
  dateCreationJuridique: 'presume blah what',
  dateEtat: 'indeed',
  dateFermetureJuridique: 'yahoo ew past',
  codeIDCC: 'across officially',
  codeTrancheEffectif: 'instantly',
  libelleTrancheEffectif: 'knowingly painfully',
  dateCessationActivite: 'swill',
  dateEffectifOfficiel: 'eek singe',
  effectifOfficiel: 'whoever',
  codeMotifCessationActivite: 'grandson privilege',
  siret: 'likewise',
  codeTypeEtablissement: 'though finally',
  libelleEnseigne: 'requite courageously',
  codeNIC: 'barring promptly',
};

export const sampleWithNewData: NewPmEtablissement = {
  idEtablissementRPG: 'illiterate as',
  codePartenaireDistributeur: 'apropos',
  numeroSiretSiege: 'as',
  codeEtat: 'so yet',
  libelleEtat: 'beneath unexpectedly earnest',
  codeCategoriePersonne: 'handsome carpool kookily',
  libelleCategoriePersonne: 'augment calmly',
  codeType: 'sprinkles black-and-white',
  dateCreationJuridique: 'truthfully',
  dateEtat: 'shameful',
  dateFermetureJuridique: 'officially inside',
  codeIDCC: 'intermesh rudely crossly',
  codeTrancheEffectif: 'slowly save',
  libelleTrancheEffectif: 'formal carelessly remarkable',
  dateCessationActivite: 'beside',
  dateEffectifOfficiel: 'ick tank abandoned',
  effectifOfficiel: 'below',
  codeMotifCessationActivite: 'profuse',
  siret: 'woot excluding',
  codeTypeEtablissement: 'oof',
  libelleEnseigne: 'jagged versus',
  codeNIC: 'whoa heartfelt',
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
