import dayjs from 'dayjs/esm';

import { IPmEntreprise, NewPmEntreprise } from './pm-entreprise.model';

export const sampleWithRequiredData: IPmEntreprise = {
  id: 29267,
  idEntrepriseRPG: 'yippee',
  codePartenaireDistributeur: 'glittering while',
  numeroSiretSiege: 'clearly hmph technician',
  codeEtat: 'duh potable',
  libelleEtat: 'ruddy',
  codeCategoriePersonne: 'mockingly appropriate suddenly',
  libelleCategoriePersonne: 'huff',
  codeType: 'unique pish',
  dateCreationJuridique: dayjs('2025-04-02'),
  dateEtat: dayjs('2025-04-01'),
  dateFermetureJuridique: dayjs('2025-04-02'),
  codeTrancheEffectif: 'gadzooks although muscat',
  libelleTrancheEffectif: 'trash plain',
  dateCessationActivite: dayjs('2025-04-02'),
  dateEffectifOfficiel: dayjs('2025-04-01'),
  effectifOfficiel: 'who although',
  codeMotifCessationActivite: 'of uh-huh comestible',
  siren: 'outfox',
  codeFormeJuridique: 'um woot consequently',
  raisonSociale: 'phooey parade',
  codeCategorieJuridique: 'chow nor exacerbate',
  codeIDCC: 'indeed toward',
  codeAPE: 'advanced zowie',
};

export const sampleWithPartialData: IPmEntreprise = {
  id: 23602,
  idEntrepriseRPG: 'left',
  codePartenaireDistributeur: 'minus per trusting',
  numeroSiretSiege: 'bowling likewise naturally',
  codeEtat: 'sociable yowza',
  libelleEtat: 'too sticker nervous',
  codeCategoriePersonne: 'cheetah',
  libelleCategoriePersonne: 'whoa commemorate',
  codeType: 'upbeat inwardly although',
  dateCreationJuridique: dayjs('2025-04-02'),
  dateEtat: dayjs('2025-04-02'),
  dateFermetureJuridique: dayjs('2025-04-01'),
  codeTrancheEffectif: 'whoever eek',
  libelleTrancheEffectif: 'an',
  dateCessationActivite: dayjs('2025-04-01'),
  dateEffectifOfficiel: dayjs('2025-04-02'),
  effectifOfficiel: 'superficial off',
  codeMotifCessationActivite: 'hammock reasonable ah',
  siren: 'oh haul',
  codeFormeJuridique: 'mooch incidentally',
  raisonSociale: 'amidst fatally ick',
  codeCategorieJuridique: 'among',
  codeIDCC: 'giving',
  codeAPE: 'supposing zowie yum',
};

export const sampleWithFullData: IPmEntreprise = {
  id: 9584,
  idEntrepriseRPG: 'chasuble pilot shrill',
  codePartenaireDistributeur: 'bog',
  numeroSiretSiege: 'dally',
  codeEtat: 'satirise ah swiftly',
  libelleEtat: 'yowza fooey brown',
  codeCategoriePersonne: 'evince',
  libelleCategoriePersonne: 'positively',
  codeType: 'measly gosh softly',
  dateCreationJuridique: dayjs('2025-04-02'),
  dateEtat: dayjs('2025-04-01'),
  dateFermetureJuridique: dayjs('2025-04-02'),
  codeTrancheEffectif: 'since',
  libelleTrancheEffectif: 'publication major',
  dateCessationActivite: dayjs('2025-04-01'),
  dateEffectifOfficiel: dayjs('2025-04-01'),
  effectifOfficiel: 'unit',
  codeMotifCessationActivite: 'consequently flood huzzah',
  siren: 'consequently',
  codeFormeJuridique: 'behind',
  raisonSociale: 'silver',
  codeCategorieJuridique: 'longboat gown hunger',
  codeIDCC: 'impact barring since',
  codeAPE: 'at uncork',
};

export const sampleWithNewData: NewPmEntreprise = {
  idEntrepriseRPG: 'playfully',
  codePartenaireDistributeur: 'whoa whimsical expostulate',
  numeroSiretSiege: 'and unwelcome',
  codeEtat: 'summarise',
  libelleEtat: 'whenever finally',
  codeCategoriePersonne: 'inasmuch statement metabolise',
  libelleCategoriePersonne: 'aftermath gadzooks',
  codeType: 'well-to-do ugh ew',
  dateCreationJuridique: dayjs('2025-04-02'),
  dateEtat: dayjs('2025-04-02'),
  dateFermetureJuridique: dayjs('2025-04-01'),
  codeTrancheEffectif: 'rough elementary an',
  libelleTrancheEffectif: 'boastfully',
  dateCessationActivite: dayjs('2025-04-02'),
  dateEffectifOfficiel: dayjs('2025-04-01'),
  effectifOfficiel: 'hungrily',
  codeMotifCessationActivite: 'rectangular regarding',
  siren: 'forenenst fraudster um',
  codeFormeJuridique: 'puritan',
  raisonSociale: 'joyous mash',
  codeCategorieJuridique: 'yet',
  codeIDCC: 'madly until mediocre',
  codeAPE: 'maestro',
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
