package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EmailAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmailAllPropertiesEquals(Email expected, Email actual) {
        assertEmailAutoGeneratedPropertiesEquals(expected, actual);
        assertEmailAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmailAllUpdatablePropertiesEquals(Email expected, Email actual) {
        assertEmailUpdatableFieldsEquals(expected, actual);
        assertEmailUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmailAutoGeneratedPropertiesEquals(Email expected, Email actual) {
        assertThat(actual)
            .as("Verify Email auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmailUpdatableFieldsEquals(Email expected, Email actual) {
        assertThat(actual)
            .as("Verify Email relevant properties")
            .satisfies(a -> assertThat(a.getAdresseEmail()).as("check adresseEmail").isEqualTo(expected.getAdresseEmail()))
            .satisfies(a -> assertThat(a.getCodeStatut()).as("check codeStatut").isEqualTo(expected.getCodeStatut()))
            .satisfies(a -> assertThat(a.getDateStatut()).as("check dateStatut").isEqualTo(expected.getDateStatut()))
            .satisfies(a -> assertThat(a.getCodeUsageEmail()).as("check codeUsageEmail").isEqualTo(expected.getCodeUsageEmail()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmailUpdatableRelationshipsEquals(Email expected, Email actual) {
        // empty method
    }
}
